die <<MESSAGE;
*************************************************************************

    ---->>> Pod::Tests is now Test::Inline! <<<----

All new versions of Pod::Tests will be distributed in Test-Inline
tarballs.  Download those instead, or better yet, use the CPAN shell.
This is a dummy package.

    ---->>> This message will self destruct <<<----

*************************************************************************
MESSAGE

