# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Tests
version:      0.17_01
version_from: lib/Pod/Tests.pm
installdirs:  site
requires:
    Test::Harness:                 1.22
    Test::More:                    0.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
